{"uuid": "ade4f919-b351-492e-83bd-b20294a65837", "children": ["8d379909-e755-43b9-87e8-fffff3ba73f7", "55cbd37f-3d80-4c4f-aeef-c11b1d79c26c", "cbdcf264-eedd-49d7-9cda-3b949389a3ba", "9706b3d4-833a-4d39-be82-ecb423f9e049", "26d99bef-607e-4da3-9e60-f9b81da2ae56", "0a64bd6c-aacc-47ec-8819-75cf110df69b", "3351b61a-3acf-45c5-8ff9-ef667be6e07c", "a98f4e55-096a-4877-8130-f268eb1402c8", "87f92318-0531-4f4f-8793-a61673379966"], "befores": [{"name": "setup_logging", "status": "passed", "start": 1730382138149, "stop": 1730382138149}], "afters": [{"name": "setup_logging::0", "status": "broken", "statusDetails": {"message": "FileNotFoundError: [Errno 2] No such file or directory: 'test.log'\n", "trace": "  File \"/Users/igor/PycharmProjects/gt_tests/env/bin/lib/python3.11/site-packages/allure_commons/_allure.py\", line 221, in __call__\n    return self._fixture_function(*args, **kwargs)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/Users/igor/PycharmProjects/gt_tests/env/bin/lib/python3.11/site-packages/_pytest/fixtures.py\", line 907, in _teardown_yield_fixture\n    next(it)\n  File \"/Users/igor/PycharmProjects/gt_tests/tests/conftest.py\", line 54, in setup_logging\n    with open(\"test.log\", \"r\") as f:\n         ^^^^^^^^^^^^^^^^^^^^^\n"}, "start": 1730382301195, "stop": 1730382301196}], "start": 1730382138149, "stop": 1730382301196}