{"uuid": "8d1ece35-c01a-49b0-965b-ead4d3ca94e9", "children": ["84bdaa75-315a-4566-9e69-9a6311408c58", "9f1721c6-9ec8-4ad6-ad44-4e25850b1b40", "ae8c8e9e-31b6-45b9-bcb9-0812019e0591", "5daa77fc-ad23-4343-a9d2-c4d1cecd494f", "d57e9b73-3210-4d25-ab54-05f29e9c6d3f", "0ec21598-04d0-4317-b58a-c363856e62b0", "04d6e8df-233e-4096-aa26-ed2fda432897", "631ec30e-b184-4c38-b2f6-6fc26d0d3696", "d629e703-441b-4145-b2ee-a9fc6d674e33"], "befores": [{"name": "setup_logging", "status": "passed", "start": 1730142842262, "stop": 1730142842262}], "afters": [{"name": "setup_logging::0", "status": "broken", "statusDetails": {"message": "FileNotFoundError: [Errno 2] No such file or directory: 'test.log'\n", "trace": "  File \"/Users/igor/PycharmProjects/gt_tests/env/bin/lib/python3.11/site-packages/allure_commons/_allure.py\", line 221, in __call__\n    return self._fixture_function(*args, **kwargs)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/Users/igor/PycharmProjects/gt_tests/env/bin/lib/python3.11/site-packages/_pytest/fixtures.py\", line 907, in _teardown_yield_fixture\n    next(it)\n  File \"/Users/igor/PycharmProjects/gt_tests/tests/conftest.py\", line 54, in setup_logging\n    with open(\"test.log\", \"r\") as f:\n         ^^^^^^^^^^^^^^^^^^^^^\n"}, "start": 1730142966205, "stop": 1730142966205}], "start": 1730142842262, "stop": 1730142966205}