{"uuid": "963e8c87-2ed7-4c68-9628-72ad21f40b97", "children": ["6510ed1a-1bfc-4d60-b194-30ecc9b87c14", "a704216f-40db-4610-bfa1-6b0db935dd8b", "a3f1abbe-c6ba-4b14-a251-a86d0d59db22", "033d3714-01c7-4bea-9884-e79c00864dc3", "e53ec9a3-3fbd-49ca-b5e6-dacc52d9f091", "5abc06ec-2b4d-4d4f-8f26-849a397e1886"], "befores": [{"name": "setup_logging", "status": "passed", "start": 1730142689295, "stop": 1730142689295}], "afters": [{"name": "setup_logging::0", "status": "broken", "statusDetails": {"message": "FileNotFoundError: [Errno 2] No such file or directory: 'test.log'\n", "trace": "  File \"/Users/igor/PycharmProjects/gt_tests/env/bin/lib/python3.11/site-packages/allure_commons/_allure.py\", line 221, in __call__\n    return self._fixture_function(*args, **kwargs)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/Users/igor/PycharmProjects/gt_tests/env/bin/lib/python3.11/site-packages/_pytest/fixtures.py\", line 907, in _teardown_yield_fixture\n    next(it)\n  File \"/Users/igor/PycharmProjects/gt_tests/tests/conftest.py\", line 54, in setup_logging\n    with open(\"test.log\", \"r\") as f:\n         ^^^^^^^^^^^^^^^^^^^^^\n"}, "start": 1730142746230, "stop": 1730142746231}], "start": 1730142689295, "stop": 1730142746231}