{"uuid": "a3dbb5bd-e00a-4ddf-8b88-4768726295ba", "children": ["18a69906-415d-4f5b-aaf0-5f7c54a19f51", "022e7207-ba2a-4b82-a0b4-3f2a7a2e9f00", "6a7a1234-5f09-4427-86dc-e388ca5322ef", "a5e2a193-937d-4a5a-8dcf-d69edbba791f", "24d122f7-d492-4f9f-a09d-f2cacf32586a", "e9a72f0d-e8c3-4b5a-a5bc-bc61daaa5bbe", "90fd487a-a210-4828-994c-d74e4e1f5688", "7ff1a186-397d-4e9a-b8be-399899ea970e", "69db10fb-cb90-4a94-aec0-3b841003cb2b"], "befores": [{"name": "setup_logging", "status": "passed", "start": 1730380549141, "stop": 1730380549141}], "afters": [{"name": "setup_logging::0", "status": "broken", "statusDetails": {"message": "FileNotFoundError: [Errno 2] No such file or directory: 'test.log'\n", "trace": "  File \"/Users/igor/PycharmProjects/gt_tests/env/bin/lib/python3.11/site-packages/allure_commons/_allure.py\", line 221, in __call__\n    return self._fixture_function(*args, **kwargs)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/Users/igor/PycharmProjects/gt_tests/env/bin/lib/python3.11/site-packages/_pytest/fixtures.py\", line 907, in _teardown_yield_fixture\n    next(it)\n  File \"/Users/igor/PycharmProjects/gt_tests/tests/conftest.py\", line 54, in setup_logging\n    with open(\"test.log\", \"r\") as f:\n         ^^^^^^^^^^^^^^^^^^^^^\n"}, "start": 1730380684057, "stop": 1730380684057}], "start": 1730380549141, "stop": 1730380684057}